name: pr

on:
  pull_request:
    branches: [master]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      # We need to run the following commands so yarn can successfully install dependencies.
      # Because node-canvas depends on cairo and pango to compile on the system, we install them here.
      - name: Install dependencies for node-canvas
        run: |
          sudo apt update
          sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
      - name: Install dependencies
        run: 'yarn install --frozen-lockfile'
      - name: Lint
        run: yarn lint
