name: pr

on:
  pull_request:
    branches: [master]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
      - name: Install
          run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
